moved to yml

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -24,8 +24,48 @@ jobs:
           default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
           echo $default | cat >default
           echo Using default scheme: $default       
-      - name: Run iOS tests
-        run: sh ./Scripts/ci-ios-code-coverage.sh
+      - name: Build and Test with Code Coverage
+        env:
+          scheme: ${{ 'default' }}
+          platform: ${{ 'iOS Simulator' }}
+        run: |
+          |
+          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
+          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
+          if [ $scheme = default ]; then scheme=$(cat default); fi
+          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
+          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
+
+          RESULT_BUNDLE="CodeCoverage.xcresult"
+          RESULT_JSON="CodeCoverage.json"
+          MIN_CODE_COVERAGE=50.0
+      
+          # Pre-clean
+          if [ -d $RESULT_BUNDLE ]; then
+            rm -rf $RESULT_BUNDLE
+          fi
+          if [ -f $RESULT_JSON ]; then
+            rm $RESULT_JSON
+          fi
+      
+          # Build
+          set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device" -enableCodeCoverage YES | xcpretty
+      
+          # Test
+          set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device" -enableCodeCoverage YES -resultBundlePath $RESULT_BUNDLE | xcpretty
+      
+          # Code coverage
+          set -o pipefail && env NSUnbufferedIO=YES xcrun xccov view --report --json $RESULT_BUNDLE > $RESULT_JSON
+          CODE_COVERAGE=$(cat $RESULT_JSON | jq '.targets[] | select( .name == "Grocery Guru" and .executableLines > 0 ) | .lineCoverage')
+          CODE_COVERAGE=$(echo $CODE_COVERAGE*100.0 | bc)
+      
+          COVERAGE_PASSES=$(echo "$CODE_COVERAGE > $MIN_CODE_COVERAGE" | bc)
+          if [ $COVERAGE_PASSES -ne 1 ]; then
+          printf "\033[0;31mCode coverage %.1f%% is less than required %.1f%%\033[0m\n" $CODE_COVERAGE $MIN_CODE_COVERAGE
+          exit -1
+          else
+          printf "\033[0;32mCode coverage is %.1f%%\033[0m\n" $CODE_COVERAGE
+          fi
       # - name: Build
       #   env:
       #     scheme: ${{ 'default' }}
