Revert run script + enabled coverage on build too

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -34,7 +34,7 @@ jobs:
           if [ $scheme = default ]; then scheme=$(cat default); fi
           if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
           file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
-          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
+          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device" -enableCodeCoverage YES
       - name: Test
         env:
           scheme: ${{ 'default' }}
@@ -46,3 +46,11 @@ jobs:
           if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
           file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
           xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device" -enableCodeCoverage YES
+          profdata_file=$(find ~/Library/Developer/Xcode/DerivedData -name '*.profdata')
+          if [ -z "$profdata_file" ]; then
+            echo "Error: No .profdata file found"
+            exit 1
+          fi
+          xcrun llvm-cov export -format="lcov" \
+          $(xcodebuild -project "$file_to_build" -scheme "$scheme" -destination "platform=$platform,name=$device" -showBuildSettings | grep -m 1 "OBJECT_FILE_DIR_normal" | awk -F '=' '{print $2}' | sed 's/^ *//g' )/x86_64/*.profdata \
+          --instr-profile $profdata_file > coverage.lcov
